### ISSUE TITLE
Error install node-red-contrib-ttn 2.0.5

### ISSUE THREAD

**Issue by ghost** [TheThingsArchive/nodered-app-node#59] opened 2019-06-06 07:17 UTC
Install 'node-red-contrib-ttn 2.0.5' in Node-red produced the following error:
2019-06-06T06:42:22.212Z Install : node-red-contrib-ttn 2.0.5

2019-06-06T06:42:21.841Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-ttn@2.0.5
2019-06-06T06:43:58.882Z [out] 
2019-06-06T06:43:58.882Z [out] > grpc@1.21.1 install /config/node-red/node_modules/grpc
2019-06-06T06:43:58.882Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2019-06-06T06:43:58.882Z [out] 
2019-06-06T06:44:03.254Z [err] node-pre-gyp
2019-06-06T06:44:03.259Z [err]  
2019-06-06T06:44:03.260Z [err] WARN
2019-06-06T06:44:03.260Z [err]  Using request for node-pre-gyp https download 
2019-06-06T06:44:04.406Z [err] node-pre-gyp
2019-06-06T06:44:04.406Z [err]  WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.21.1/node-v64-linux-arm-musl.tar.gz 
2019-06-06T06:44:04.407Z [err] node-pre-gyp 
2019-06-06T06:44:04.407Z [err] WARN Pre-built binaries not found for grpc@1.21.1 and node@10.14.2 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
2019-06-06T06:44:04.407Z [err]  
2019-06-06T06:44:15.198Z [err] gyp
2019-06-06T06:44:15.206Z [err]  
2019-06-06T06:44:15.207Z [err] ERR!
2019-06-06T06:44:15.207Z [err]  build error
2019-06-06T06:44:15.208Z [err]  
2019-06-06T06:44:15.212Z [err] gyp
2019-06-06T06:44:15.213Z [err]  ERR! 
2019-06-06T06:44:15.213Z [err] stack Error: not found: make
2019-06-06T06:44:15.213Z [err] gyp
2019-06-06T06:44:15.213Z [err]  ERR!
2019-06-06T06:44:15.214Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-06-06T06:44:15.214Z [err] gyp ERR!
2019-06-06T06:44:15.215Z [err]  stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-06-06T06:44:15.215Z [err] gyp 
2019-06-06T06:44:15.215Z [err] ERR! stack
2019-06-06T06:44:15.216Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-06-06T06:44:15.216Z [err] gyp
2019-06-06T06:44:15.216Z [err]  ERR! stack
2019-06-06T06:44:15.216Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-06-06T06:44:15.216Z [err] gyp
2019-06-06T06:44:15.217Z [err]  ERR! 
2019-06-06T06:44:15.217Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-06-06T06:44:15.217Z [err] gyp
2019-06-06T06:44:15.217Z [err]  ERR! 
2019-06-06T06:44:15.218Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-06-06T06:44:15.218Z [err] gyp ERR!
2019-06-06T06:44:15.219Z [err]  stack     at FSReqWrap.oncomplete (fs.js:154:21)
2019-06-06T06:44:15.220Z [err] gyp
2019-06-06T06:44:15.221Z [err]  ERR! System
2019-06-06T06:44:15.221Z [err]  Linux 4.14.98-v7
2019-06-06T06:44:15.222Z [err] gyp
2019-06-06T06:44:15.223Z [err]  ERR! command
2019-06-06T06:44:15.223Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-musl" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
2019-06-06T06:44:15.223Z [err] gyp 
2019-06-06T06:44:15.224Z [err] ERR! cwd
2019-06-06T06:44:15.224Z [err]  /config/node-red/node_modules/grpc
2019-06-06T06:44:15.224Z [err] gyp
2019-06-06T06:44:15.225Z [err]  ERR!
2019-06-06T06:44:15.225Z [err]  node -v v10.14.2
2019-06-06T06:44:15.225Z [err] gyp 
2019-06-06T06:44:15.226Z [err] ERR! 
2019-06-06T06:44:15.226Z [err] node-gyp -v v3.8.0
2019-06-06T06:44:15.226Z [err] gyp 
2019-06-06T06:44:15.227Z [err] ERR! not ok
2019-06-06T06:44:15.227Z [err]  
2019-06-06T06:44:15.240Z [err] node-pre-gyp
2019-06-06T06:44:15.241Z [err]  ERR! build error
2019-06-06T06:44:15.241Z [err]  
2019-06-06T06:44:15.245Z [err] node-pre-gyp
2019-06-06T06:44:15.245Z [err]  ERR! stack
2019-06-06T06:44:15.246Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-musl --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
2019-06-06T06:44:15.246Z [err] node-pre-gyp ERR!
2019-06-06T06:44:15.246Z [err]  stack
2019-06-06T06:44:15.246Z [err]      at ChildProcess.<anonymous> (/config/node-red/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2019-06-06T06:44:15.246Z [err] node-pre-gyp 
2019-06-06T06:44:15.247Z [err] ERR! stack
2019-06-06T06:44:15.247Z [err]      at ChildProcess.emit (events.js:182:13)
2019-06-06T06:44:15.247Z [err] node-pre-gyp 
2019-06-06T06:44:15.247Z [err] ERR! 
2019-06-06T06:44:15.253Z [err] stack     at maybeClose (internal/child_process.js:962:16)
2019-06-06T06:44:15.253Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
2019-06-06T06:44:15.253Z [err] node-pre-gyp ERR! System Linux 4.14.98-v7
2019-06-06T06:44:15.253Z [err] node-pre-gyp
2019-06-06T06:44:15.258Z [err]  ERR! command "/usr/bin/node" "/config/node-red/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
2019-06-06T06:44:15.259Z [err] node-pre-gyp ERR! cwd /config/node-red/node_modules/grpc
2019-06-06T06:44:15.259Z [err] node-pre-gyp ERR! node -v v10.14.2
2019-06-06T06:44:15.259Z [err] node-pre-gyp ERR! node-pre-gyp -v v0.13.0
2019-06-06T06:44:15.259Z [err] node-pre-gyp ERR! not ok 
2019-06-06T06:44:15.262Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/config/node-red/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-musl --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
2019-06-06T06:44:20.081Z [err] npm
2019-06-06T06:44:20.082Z [err]  
2019-06-06T06:44:20.083Z [err] ERR! code ELIFECYCLE
2019-06-06T06:44:20.084Z [err] npm
2019-06-06T06:44:20.085Z [err]  ERR! errno
2019-06-06T06:44:20.085Z [err]  1
2019-06-06T06:44:20.095Z [err] npm
2019-06-06T06:44:20.096Z [err]  ERR! grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2019-06-06T06:44:20.096Z [err] npm 
2019-06-06T06:44:20.096Z [err] ERR! Exit status 1
2019-06-06T06:44:20.097Z [err] npm
2019-06-06T06:44:20.097Z [err]  ERR! 
2019-06-06T06:44:20.098Z [err] npm ERR!
2019-06-06T06:44:20.098Z [err]  Failed at the grpc@1.21.1 install script.
2019-06-06T06:44:20.098Z [err] npm
2019-06-06T06:44:20.098Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-06-06T06:44:20.481Z [err] 
2019-06-06T06:44:20.483Z [err] npm ERR! A complete log of this run can be found in:
2019-06-06T06:44:20.483Z [err] npm ERR!     /root/.npm/_logs/2019-06-06T06_44_20_345Z-debug.log
2019-06-06T06:44:20.562Z rc=1

**Comment by johanstokking** [comment] 2019-06-11 09:35
Is this a duplicate of https://github.com/TheThingsNetwork/nodered-app-node/issues/44 ?

**Comment by To1952P** [comment] 2019-06-12 06:50
I have no idea. The above debug notification is from the Raspberry PI. Alternatively I have installed node-red on windows and then installed node-red-contrib-ttn@2.0.5 via Pallette. Again the following error messages. It may have to do with accessing a Git link

-----------------------------------------------------------
2019-06-12T06:42:13.974Z Install : node-red-contrib-ttn 2.0.5

2019-06-12T06:42:13.982Z npm.cmd install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-ttn@2.0.5
2019-06-12T06:42:43.804Z [err] npm 
2019-06-12T06:42:43.804Z [err] ERR! path git
2019-06-12T06:42:43.804Z [err] npm ERR!
2019-06-12T06:42:43.804Z [err]  code ENOENT
2019-06-12T06:42:43.804Z [err] npm ERR!
2019-06-12T06:42:43.804Z [err]  errno ENOENT
2019-06-12T06:42:43.804Z [err] npm
2019-06-12T06:42:43.804Z [err]  ERR! syscall
2019-06-12T06:42:43.804Z [err]  spawn git
2019-06-12T06:42:43.806Z [err] npm ERR! 
2019-06-12T06:42:43.806Z [err] enoent Error while executing:
2019-06-12T06:42:43.806Z [err] npm ERR! enoent undefined ls-remote -h -t https://github.com/thethingsnetwork/api.git
2019-06-12T06:42:43.806Z [err] npm
2019-06-12T06:42:43.806Z [err]  ERR! enoent 
2019-06-12T06:42:43.806Z [err] npm ERR! 
2019-06-12T06:42:43.806Z [err] enoent 
2019-06-12T06:42:43.806Z [err] npm 
2019-06-12T06:42:43.806Z [err] ERR! enoent spawn git ENOENT
2019-06-12T06:42:43.806Z [err] npm ERR! 
2019-06-12T06:42:43.806Z [err] enoent This is related to npm not being able to find a file.
2019-06-12T06:42:43.806Z [err] npm ERR! 
2019-06-12T06:42:43.806Z [err] enoent 
2019-06-12T06:42:44.038Z [err] 
2019-06-12T06:42:44.038Z [err] npm ERR! A complete log of this run can be found in:
2019-06-12T06:42:44.038Z [err] npm ERR!     C:\Users\tonpi\AppData\Roaming\npm-cache\_logs\2019-06-12T06_42_43_808Z-debug.log
2019-06-12T06:42:44.061Z rc=1

**Comment by theArcher73** [comment] 2019-08-09 15:20
I have the same problem on Raspberry Pi 3b+.
Has everybody an idea to solve the problem? The same exceptions occurs when I try to Install the node-red-contrib-ttn over the Website NodeRed


pi@CL1NodeRed:~/.node-red $ npm install node-red-contrib-ttn
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/thethingsnetwork/api.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-08-09T15_15_43_731Z-debug.log

**Comment by johanstokking** [comment] 2019-08-09 15:28
Is this the same as https://github.com/TheThingsNetwork/nodered-app-node/issues/44 ?

**Comment by theArcher73** [comment] 2019-08-09 16:00
no, nodeRed starts with some warnings but I cant install in the Palette....

**Comment by theArcher73** [comment] 2019-08-09 16:01
pi@CL1NodeRed:~/.node-red $ node-red-pi --max-old-space-size=256
9 Aug 18:00:36 - [info]

Welcome to Node-RED
===================

9 Aug 18:00:36 - [info] Node-RED version: v0.20.7
9 Aug 18:00:36 - [info] Node.js  version: v10.16.2
9 Aug 18:00:36 - [info] Linux 4.19.42-v7+ arm LE
9 Aug 18:00:37 - [info] Loading palette nodes
9 Aug 18:00:41 - [info] Settings file  : /home/pi/.node-red/settings.js
9 Aug 18:00:41 - [info] Context store  : 'default' [module=memory]
9 Aug 18:00:41 - [info] User directory : /home/pi/.node-red
9 Aug 18:00:41 - [warn] Projects disabled : editorTheme.projects.enabled=false
9 Aug 18:00:41 - [info] Flows file     : /home/pi/.node-red/flows_CL1NodeRed.json
9 Aug 18:00:41 - [info] Creating new flow file
9 Aug 18:00:41 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

9 Aug 18:00:41 - [info] Starting flows
9 Aug 18:00:41 - [info] Started flows
9 Aug 18:00:41 - [info] Server now running at http://127.0.0.1:1880/

**Comment by johanstokking** [comment] 2019-08-12 06:25
@theArcher73 please see the problem in that issue; it's also related to installation, but then through CLI and not through the palette.

**Comment by johanstokking** [comment] 2019-08-22 13:42
RPi support is now deprecated. We'll add guides for V3 to work with builtin Node-RED nodes (i.e. the MQTT input and output nodes)

**Closed as completed by johanstokking** 2019-08-22 13:42 UTC
